name: 'tpch_project'
version: '1.0.0'
config-version: 2

profile: 'default'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # Directory where dbt will store compiled SQL files and other artifacts.
clean-targets:  # Directories dbt will clean when you run dbt clean.
  - "target"
  - "dbt_modules"

models:
  tpch_project:
    # Applies to all files under models/
    +materialized: view  # Change to 'table' if you prefer materializing as tables.
    staging:
      +materialized: view
      +schema: staging  # Prefix added to the schema, models will be in 'staging' schema.
      tpch:
        +schema: tpch  # Models under models/tpch will be in 'tpch' schema.
